Fix deploy script

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -6,6 +6,25 @@ GREEN='\033[0;32m'
 NC='\033[0m'
 
 init () {
+    if [ -f .env ]; then
+        while true; do
+            read -e -p "[$(printf "${YELLOW}WARNING${NC}")] Environment file already exists! Do you want overwrite file? This is can cause errors! (y/n) " yn
+
+            case $yn in 
+	            [yY])
+                    break
+                ;;
+	            [nN])
+                    echo Exit
+		            exit
+                ;;
+	            *)
+                    echo invalid response
+                ;;
+            esac
+        done
+    fi
+
 # Get User Email Address
     while [[ ! $USER_EMAIL =~ ^.+@.+\..+$ ]] || [[ $USER_EMAIL == '' ]]
     do
@@ -60,6 +79,7 @@ init () {
 
     read -e -p "Enter Keycloak Admin Username: " -i "admin" KEYCLOAK_ADMIN_USERNAME
     read -e -p "Enter Keycloak Realm for Outline: " -i "outline" KEYCLOAK_REALM_NAME
+    read -e -p "Enter Keycloak OIDC ClientID for Outline: " -i "outline_app" KEYCLOAK_CLIENT_ID
     KEYCLOAK_ADMIN_PASSWORD=$(pass_gen 16)
     KEYCLOAK_CLIENT_SECRET=$(pass_gen 32)
 
@@ -99,12 +119,33 @@ MINIO_BUCKET_PASSWORD=$MINIO_BUCKET_PASSWORD
 
 # KEYCLOAK
 KEYCLOAK_REALM_NAME=$KEYCLOAK_REALM_NAME
+KEYCLOAK_ADMIN_USERNAME=$KEYCLOAK_ADMIN_USERNAME
+KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
+KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID
 KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET
 
 # OUTLINE
 OUTLINE_SECRET_KEY=$OUTLINE_SECRET_KEY
 OUTLINE_UTILS_SECRET=$OUTLINE_UTILS_SECRET
 EOF
+}
+
+deploy () {
+    if ! [ -f .env ]; then
+        init
+    fi
+
+    source .env
+
+    docker-compose -f keycloak/docker-compose.yml up -d
+
+    docker-compose -f keycloak/docker-compose.yml exec keycloak /opt/jboss/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth/ --realm master --user $KEYCLOAK_ADMIN_USERNAME --password $KEYCLOAK_ADMIN_PASSWORD
+    docker-compose -f keycloak/docker-compose.yml exec keycloak /opt/jboss/keycloak/bin/kcadm.sh create realms -s realm=$KEYCLOAK_REALM_NAME -s enabled=true
+    docker-compose -f keycloak/docker-compose.yml exec keycloak /opt/jboss/keycloak/bin/kcadm.sh create clients -r $KEYCLOAK_REALM_NAME -s enabled=true -s rootUrl="https://${OUTLINE_DOMAIN}" -s clientId="${$KEYCLOAK_CLIENT_ID}" -s redirectUris="[\"https://${OUTLINE_DOMAIN}/*\"]" -s webOrigins="[\"https://${OUTLINE_DOMAIN}/\"]" -s adminUrl="https://${OUTLINE_DOMAIN}" -s secret="${$KEYCLOAK_CLIENT_SECRET}"
+
+    docker-compose -f minio/docker-compose.yml up -d
+    docker-compose -f outline/docker-compose.yml up -d
+    docker-compose -f traefik/docker-compose.yml up -d
 }
 
 pass_gen () {
@@ -117,11 +158,31 @@ hash_gen () {
     echo $(openssl rand -hex $len)
 }
 
+help () {
+    cat <<EOF
+Outline Docker Deploy Script
+
+    init    - Create .env file with required parameters.
+    deploy  - Run deploy of application.
+    help    - Shows this help text.
+
+v.0.0.1
+
+EOF
+}
+
 case "$1" in
     init)
         init
     ;;
+    help)
+        help
+    ;;
+    deploy)
+        deploy
+    ;;
     *)
-        printf "[${RED}ERROR${NC}] Unknown command\n"
+        printf "[${RED}ERROR${NC}] Unknown command\n\n"
+        help
     ;;
 esac
